import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import MemeListItem from '../components/MemeListItem';

export default function Home() {
  const [data, setData] = useState({ memes: [] });
  const [isLoading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    fetch('https://api.imgflip.com/get_memes')
      .then((res => res.json()))
      .then((data) => {
        setData(data.data);
        setLoading(false);
      })
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Top memes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          See the top memes of this month
        </h1>

        {isLoading ? <p>Loading...</p>: <div>
          <ul className={styles.listContainer}>
          {data.memes.map((meme: Meme): JSX.Element => <MemeListItem key={meme.id} meme={meme} />)}
          </ul></div>}
      </main>
    </div>
  )
}
